### PR TITLE
fix directionality fixes #406

### LINKED ISSUE #406: The toolbar icon should not change when switching to RTL layout
The game toolbar and navigation toolbar's icons should not change when switching to the RTL layout. But now it changed.

See:
https://github.com/calcitem/Sanmill/issues/241
Commit 9fb44f204f45af8188b39c247a581e06c8e2cc88

Git tag v1.1.38 does not have this problem.

Thanks!

### PR DESCRIPTION
**Pull request by Leptopoda**
## :scroll: Description

Fixes and cleans up how we handle single direction icons (now handling them propperly :upside_down_face:).
The nav_toolbar has been fixed and verified.
Please thoroughly test the directionality of the other icons (mainly the AppBar tooltip thingy). Thing like when winning is the arrow for the winner the correct way? ...

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by calcitem** [comment]
LGTM. You can squash and merge. Thanks!

**Comment by Leptopoda** [comment]
why did you change this?

I don't want to manually check for the directionality. The `Directionality` widget should be used to control it. 
As you can see I've wrapped the `header` with one. I've hard encoded the directionality meaning that it should not change once we are in rtl.
Now you checking for it manually (`final ltr = Directionality.of(context) == TextDirection.ltr;`) is actually redundant as the closest Directionality widget in the widget tree (the one that's checked with `.of(context)`) is hard encoded so the chedck will always be true.

The checks should be redundant. If this isn't the case we should use a builder as it might be that the wring build context is used but that shouldn't be used.

So:
What where your intentions?

**Comment by calcitem** [comment]
Indeed my modification is really rough.  

My intention is to swap the left and right positions of player1 and player2 icons to make them consistent with the behavior of git tag v1.1.38.  At that time, this layout has been confirmed by an Iranian user and meets his expectations.

**Comment by Leptopoda** [comment]
Ah I understand. 
you mean like:
ltr [Player X] > [Player Y]
rtl [Player Y] < [Player X]

**Comment by calcitem** [comment]
Yes!

**Comment by Leptopoda** [comment]
should be done

**Comment by calcitem** [comment]
The direction of who won was reversed.

**Comment by Leptopoda** [comment]
ok looking into it seems like the icon used in this case is not directional (not matching the closest ancestors TextDirection)

```dart
  /// fluent icon named "toggle_right" in size 24 and regular style.
  static const IconData toggle_right_24_regular = IconData(0xf82c, fontFamily: 'FluentSystemIcons-Regular', fontPackage: _kFontPkg);
```

I'll open an issue with microsoft and ask wether this is intentional. If it is I'll write an extension method for the needed Icons :)

**Comment by calcitem** [comment]
Since Microsoft adds left/right to the file name of this icon, it means that this icon cannot adapt to changes in layout, because the definition of left and right is the same regardless of the country and region.

**Comment by Leptopoda** [comment]
The why is the chevron directional? 🙃

**Comment by calcitem** [comment]
I think Microsoft would not solve this problem in the short term. It is recommended that this fix be merged first.

**Comment by Leptopoda** [comment]
There is no reason as I already incorporated it into the big PR. 
 
Merging now would only result in conflicts 🙃

**Pull request closed without merging**
