### PR TITLE
Config rework

### PR DESCRIPTION
**Pull request by Leptopoda**
DO NOT MERGE!
this is the first proposed version for the new storage backend.

You can audit and test the new code.
Currently the migration does not seem to work so I'll debug this tomorrow.

Also sorry for the PR in the other repo. GH auto selected it as we are still marked as a fork. As this project seems to independent we should probably remove the fork dependency all together.

### CODE REVIEW

**Comment by calcitem** [comment]
I've been in touch with the author of NineChess from the upstream repository, and he knows that Sanmill has evolved into a mobile app. He says he no longer maintains the NineChess project and is happy to see Sanmill continue to grow, and expects the community to continue to make the Mill app great.

I'm not sure how to disconnect dependencies from upstream while preserving the Git commit history to avoid confusing project participants. I've tried to do this before, but haven't found a way.

**Comment by Leptopoda** [comment]
ok never mind the migration works just fine.
Can you conduct further testing??

also when this is merged we can also nearly merge #306

**Comment by calcitem** [comment]
OK I will do a test.

**Comment by calcitem** [comment]
I ran `./flutter-init.sh` and open Android Studio to build but failed:

```shell
$ flutter build apk --debug

Running Gradle task 'assembleDebug'...
lib/models/color.dart:26:6: Error: Error when reading 'lib/models/color.g.dart': No such file or directory
part 'color.g.dart';
     ^

lib/services/storage/storage.dart:79:41: Error: Method not found: 'ColorSettingsAdapter'.
    Hive.registerAdapter<ColorSettings>(ColorSettingsAdapter());
                                        ^^^^^^^^^^^^^^^^^^^^
```

**Comment by calcitem** [comment]
Do I need to rebase the dev branch first? But there are a lot of conflicts between the two branches.

**Comment by calcitem** [comment]
After launching the app, after about a few seconds, an exception appears without clicking on the screen, as follows.

```dart
exception = {LateError} LateInitializationError: Field '_drawSoundId@1008306828' has already been initialized.
 _stackTrace = null
 _message = "Field '_drawSoundId@1008306828' has already been initialized."
fieldName = "_drawSoundId@1008306828"

LateError._throwFieldAlreadyInitialized (internal_patch.dart:211)
Audios._drawSoundId (audios.dart:47)
Audios.loadSounds (audios.dart:65)
<asynchronous gap>
```

**Comment by calcitem** [comment]
When choosing a different algorithm, the value stored in LocalDatabase doesn't feel right?

Since testing whether the algorithm works is a bit tricky, I didn't try the actual validity of the different algorithms for now but just saw from the log that it doesn't seem to work as expected.

```
I/flutter (29811): [game_settings_page] algorithm = 0
I/flutter (29811): [game_settings_page] LocalDatabaseService.preferences.algorithm: 2
I/flutter (29811): [game_settings_page] algorithm = 1
I/flutter (29811): [game_settings_page] LocalDatabaseService.preferences.algorithm: 0
I/flutter (29811): [game_settings_page] algorithm = 2
I/flutter (29811): [game_settings_page] LocalDatabaseService.preferences.algorithm: 1
I/flutter (29811): [game_settings_page] algorithm = 0
I/flutter (29811): [game_settings_page] LocalDatabaseService.preferences.algorithm: 2
I/flutter (29811): [game_settings_page] algorithm = 2
I/flutter (29811): [game_settings_page] LocalDatabaseService.preferences.algorithm: 0
```

From the `[uci] input: setoption name Algorithm value N` command, it seems that the configuration sent to the backend engine is working, so only the log is just incorrect?

**Comment by Leptopoda** [comment]
I know about the problem. But that is something that got introduced by #284. I'll fix that but in a separate commit. 

And yes this commit depends on build_runner but as this branch was still based on master and not dev the build_runner wasn't activated in the build script.

**Comment by calcitem** [comment]
> Did the migration work?

Yes.

**Comment by calcitem** [comment]
The setting of mainToolbarBackgroundColor does not take effect.

**Comment by Leptopoda** [comment]
> The setting of mainToolbarBackgroundColor does not take effect.

I had a typo there. Might still be related to that. I'll have a look.

**Comment by calcitem** [comment]
> > Dynamic switching of languages does not work correctly now.
> 
> There already is a confirmation dialog. 🤷‍♀️

Sorry, this is a false alarm. There is indeed a dialog box.

**Comment by calcitem** [comment]
Every commit should work to be expected, so it is unnecessary to ensure that every branch is based on the master branch, and I suggest that this branch be rebased to the dev branch later.

**Comment by Leptopoda** [comment]
> mainToolbarBackgroundColor

works for me

> The passive option is not in effect, and when the passive switch is tapped, the log prints out:

also works for me

> The piecesCount option is not in effect, and when the piecesCount setting is changed, the log prints out:

I see what happened there. The `Rule`object (wich updates the engine) is not updated after `Rules` get changed. I'll fix that.

**Comment by calcitem** [comment]
The nMoveRule is 100. But in the following move list, less than ten moves and the game is over, which means there is also a problem with this configuration. The reason may be the same as the one you just mentioned.

```
1.     d6    b4
 2.     f4    d2
 3.     f6    b6
 4.     f2xb4    b2
 5.     b4    d3
 6.     d1    d7
 7.     g4    a7
 8.     e4xd7    a4
 9.     a1    c4
10.    g4-g1xb6    a7-d7
11.    b4-b6xc4    d7-a7
12.    g1-g4xd3    a7-d7
13.    e4-e3    d7-a7
14.    d6-d7    a4-b4
15.    e3-d3    b4-a4
16.    d3-c3    a4-b4
```

**Comment by calcitem** [comment]
Many entries in the `Open source licenses` are followed by `null`. Maybe an earlier modification has introduced this.

**Comment by calcitem** [comment]
When developer mode is enabled, the original function of restoring default settings is disabled and is now in effect. 

The reason why the function of restoring default settings needs to be disabled is that in the Monkey test, it is necessary to prevent Monkey from randomly clicking on some links that lead to jumping to the web browser and cannot return to the app GUI. If the function of restoring default settings is not disabled, the default settings may be restored randomly in the Monkey test and it will turn off the developer mode, resulting in the following Monkey test appears abnormal.

**Comment by calcitem** [comment]
Double-clicking on the big word Mill should only show the configuration items for the developer options instead of turning on developer mode by default. As stated in a post above, the reason for this is that when developer mode is enabled, some features will not respond to user taps. And the user is likely to double-click on Mill by accident, and everything that follows may make the user think that an exception has occurred.

**Comment by Leptopoda** [comment]
> For file naming, toolbar is an English word and does not need to be written as tool_bar.

ups. My bad. 
would you please track this, the licence thingy and the audio late init error from above in #303 as regressions. All of them where introduces in #284  and we should probably do a followup to that seperately.

**Comment by calcitem** [comment]
I am not sure if these two lines can be removed from .gitignore.

```
# Sanmill Settings
sanmill_settings.json
```

**Comment by calcitem** [comment]
> > For file naming, the toolbar is an English word and does not need to be written as a tool_bar.
> 
> ups. My bad. Would you please track this, the license thingy, and the audio late init error from above in #303 as regressions? All of them were introduces in #284, and we should probably do a follow-up to that separately.

Okay, I will create a few issues that are not related to this change.

**Comment by calcitem** [comment]
> It would also be better if you would use the dev branch for future commits :)

You can continue to use the current dev branch.
I can also migrate to this branch and continue committing so that we don't have to do a merge.

> What about doing a single comment with all findings (in a list)?
> It's way easier to go through them that way.

OK, I'll put it all together, I posted multiple posts before because it was like getting you a quick email alert.

**Comment by calcitem** [comment]
334367b

Buglist: 

- [ ] The passive option is not in effect

(Editing)

**Comment by calcitem** [comment]
> seems to be there even before the commit (can't find a reference to this color anywhere in the code

Confirm that this problem does not exist in git tag v1.1.38.

**Comment by Leptopoda** [comment]
> Confirm that this problem does not exist in git tag v1.1.38. 

an issue should be opened for that.

the other bug should be resolved.

**Pull request merged**
