### PR TITLE
deprecate developer mode

### PR DESCRIPTION
**Pull request by Leptopoda**
## :scroll: Description
removes the ability to enable the developer mode in production.

## :bulb: Motivation and Context

We shouldn't ship it to users (performance, app size, etc) so it's hidden behind compile time configs.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Review by calcitem — COMMENTED** [review]
The performance and size impact of removing the developer mode is minimal. Sometimes it is necessary for the user to perform an automatic play test based on his own mobile phone to reproduce the problem, so it is necessary to keep it.

**Comment by Leptopoda** [comment]
I don't get the point.
How does the developer mode help the user to make an automated test?

Also why should a user do this stuff?

**Comment by calcitem** [comment]
Automatic restart is definitely necessary, and some users want to confirm whether the draw rate has improved. If it must be removed, this option needs to be explicitly opened to users.

**Comment by calcitem** [comment]
Android phones also retain the dev mode in the release build. I don't understand what is wrong with retaining the dev mode.

**Comment by Leptopoda** [comment]
> Android phones also retain the dev mode in the release build. I don't understand what is wrong with retaining the dev mode.

The android developer settings introduce advanced settings for developing and debugging android app. Every user experienced enough to use logcat and debug the app should build the app themselves.
Our DevMode does not implement any such functionality someone would need but couldn't get without a 5min build.

Also IMO the risk of someone accidentally enabling them is to high. When they are enabled they're presented with wired characters on the board... this would severely degrade the UX. 
It seems like you thought of that as well so the Temp class was born. Finding the developer mode would not auto enable them. 

IMO the risk of a degraded UX is not worth maintaining the more complex code as this isn't really needed in production.

**Comment by calcitem** [comment]
The original way of activating DevMode is after a number of consecutive clicks. After the modification is activated by double-clicking, it is of course easy to trigger accidentally.

**Comment by Leptopoda** [comment]
but I don't think changing that would justify the added code complexity for realistically no improvements to the UX.

**Comment by calcitem** [comment]
As long as the auto replay option is opened up for users to set up, I have no objection to removing the dev mode.

Environment variables help identify whether the user's apk source is GitHub or F-Droid, or the apk compiled locally, but if there are other alternatives, it can be removed.

**Comment by Leptopoda** [comment]
ok I'll expose the auto replay feature in a follow up commit. 
Is there any reason we need the environment variables? They contain quite some private info about the developer and I don't see why we would need it in production? We could just ask the user where they installed it from if that is the reason.

**Comment by calcitem** [comment]
The production version can only be built by the CI server and cannot contain private information.

Sometimes the blind friend himself has forgotten where the current version came from, and it has been messed up to change it. In this case, I can ask him to send environment variables.

**Comment by Leptopoda** [comment]
I'll have a think and will come up with a fix (probably a separate commit though)

at least all the other PR's are fine so I can finalize the work of restructuring the game logic stuff :)

**Comment by Leptopoda** [comment]
Ok just to know is there nay other reason for the enviornment variables? Could they be deleted if the app was aware of the build version?

**Comment by calcitem** [comment]
As discussed in another issue before, there is currently no solution to automatically bring the git commit id in every compilation, which makes the version number of the apk compiled by the server the same as the one compiled locally.

**Comment by Leptopoda** [comment]
Another few questions:

- why do we need the source of the apk at all? The app should run the same no matter where it is compiled.

**Comment by calcitem** [comment]
Different sources may use different Flutter versions, etc. Some bugs are caused by third-party SDKs.  Sometimes the updated version configuration may not be timely.  The compilation of F-Droid is executed on a regular basis, which cannot be precisely controlled by us.

**Comment by Leptopoda** [comment]
> Different sources may use different Flutter versions, etc. Some bugs are caused by third-party SDKs.

Everyone experiencing bugs with a different SDK version (aka they self build) should be able to also report the SDK version themselves (when reporting the issue). We could constrain the flutter version in pubspec.yaml (although I don't think this would be a great idea). 

> Sometimes the updated version configuration may not be timely.

what do you mean by that?

> The compilation of F-Droid is executed on a regular basis, which cannot be precisely controlled by us.

F-Droid is only looking for changes on master. As we already said we will only push to master when we make a new release thus every F-Droid build will have a different build number. It isn't needed in that case.

**Comment by calcitem** [comment]
F-droid finds new versions based on git tag, and has nothing to do with the branch management model.  The problem is that the maintainers of F-droid will modify the configuration from time to time so that the app is compiled with the new version of Flutter, which may be inconsistent with the apk released on the Play Store.  However, the Flutter version is not important. I have already realized it. The above is just an example.

**Comment by Leptopoda** [comment]
As discussed I've moved the auto restart option out of the developer settings. 
I've also deprecated the entire UI of them (strings have to be removed later). 

The environment config page also has been removed (I've said my reasons and still can't find any valid use case).


The PR is ready for a final review

**Comment by calcitem** [comment]
So sorry that I didn't review the code carefully before, and after reviewing it, I found that it seemed different from what I expected, and we need to discuss it more.

I initially thought you would modify it to delete the environment variables from the developer mode, move Auto Restart to the outside, and then delete the developer mode in the production mode. Still, it can be turned on by `--dart-define`.  There are no other changes.

Expand the discussion below:

* removes the ability to enable the developer mode in production.

Isn't it just removed in the production environment and kept in the debug environment? Why do you want to remove the string resource?  I initially thought it would continue to control through `--dart-define`.

If the developer mode is deleted, how to debug the screen reader? I mean, it was previously able to be controlled through the developer mode.

If the commented code is deleted, the developer mode is deleted, and we don't like the existence of many Git branches, how can we debug this feature? Can we only rely on rolling back the code to reapply the changes?

* _setExperimentsEnabled

Why should this feature be deleted? It is common practice to add experimental features in many programs such as Firefox/Chrome/YouTube/Facebook/WeChat. I don't want to maintain a separate Git branch for unstable features.

* Sound effects 

The function of Sound effects will be added in the future. Different sound themes will be supported, one is the current imitation sound, and the other is the cute sound children like.

**Comment by calcitem** [comment]
It seems that the effect of the modification is: the dev mode option is completely removed from the GUI, but can it be enabled by `--dart-define`? If this is the behavior, it's OK.

**Comment by Leptopoda** [comment]
>  I initially thought it would continue to control through --dart-define.

Thats what the first commit did.

> If the developer mode is deleted, how to debug the screen reader? I mean, it was previously able to be controlled through the developer mode.

screen reader settings already are outside the developer settings so that hasn't changed.

> If the commented code is deleted, the developer mode is deleted, and we don't like the existence of many Git branches, how can we debug this feature? Can we only rely on rolling back the code to reapply the changes?

> Why should this feature be deleted? It is common practice to add experimental features in many programs such as Firefox/Chrome/YouTube/Facebook/WeChat. I don't want to maintain a separate Git branch for unstable features in release version.

I deprecated the experiments and they are now controlled by the compile time config.


Long story short:
> It seems that the effect of the modification is: the dev mode option is completely removed from the GUI, but can it be enabled by --dart-define? If this is the behavior, it's OK.

everything done by the dev mode is now done by the compile time flag :upside_down_face: 

> It is very difficult to synchronize the action of removal to other 44 languages by POEditor, and it will be more complicated to restore it later. Maybe Weblate is easy to do, but I haven't delved into it yet.

I think we should talk to the translators  wether we wanna change the platform :woman_shrugging:.  I thought that less strings means less works to translate new languages ...

**Comment by calcitem** [comment]
> I deprecated the experiments and they are now controlled by the compile time config.

The current practice rule is that all apk provided to users MUST be constructed by the server. 

If the experimental features are also controlled by options at build time, how do we pass parameters to Github Action to control the experimental features enable or disable?  If it doesn't work, we can only create an additional yml file to build experimental features. But I don't want to waste server resources and let it be triggered every time.

**Comment by Leptopoda** [comment]
We could introduce a separate compile time config like `beta` or `experimental` and build a separate apk for the play beta channel?

**Comment by calcitem** [comment]
If the beta channel has no bad feedback after a period of user trial, this version will be directly pushed to the official channel, that is, app will not be rebuilt again, because there may be differences introduced due to changes in the compilation environment when rebuilding  and lead to the occurrence of some unexpected situations. 

In addition, during the COVID now, Google’s review efficiency has been significantly reduced, so I don’t want to upload a new apk and go through the review process again.

In addition, as I just said, maintaining 3 apks for devmode, experimental, and monkey will significantly increase the number of server compilations. I feel sorry.  If these 3 merged into 1 yml, that is, 3 apk files are generated for each compilation, which can be reluctantly accepted, but this will further increase the compilation time of the original 8 minutes, and will also reduce the development efficiency.

**Comment by Leptopoda** [comment]
why should the ci build the dev mode version?

**Comment by calcitem** [comment]
Because need to take the devmode apk to Tencent's WeTest laboratory for large-scale monkry testing.

**Comment by Leptopoda** [comment]
dev mode is still not related to monkey tests. Thats the monkey apk.

Also monkey tests should only need to be run for new releases so for PRs from dev -> master so this wouldn't really harm the development workflow

**Comment by calcitem** [comment]
How do you deal with the part of the code that displays the grid coordinates on the mill board?  This part is used to debug screen reader functions.

**Comment by calcitem** [comment]
Can be merged.

**Pull request merged**
