### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by calcitem**
Create a list of Sanmill team members' GitHub handles who are suggested reviewers for contributions to this repository.

These names are just suggestions. It is fine to have your changes reviewed by someone else.

### CODE REVIEW

**Review by Leptopoda — CHANGES_REQUESTED** [review]
According to the [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location) the file should be either in `.github/` or `docs/` I'd prefer the first one but it has to be changed either way.

Also I'd suggest adding a catchall like `/`
Why did you add `.vscode/` and not the IDEA equivalent `.run/`

**Comment by calcitem** [comment]
So far, I didn't see there is any configuration file suitable for under version control in .run.

**Comment by Leptopoda** [comment]
.run is contains the equivalent to .vscode so it would be inconsistent to include one but not the other

**Comment by Leptopoda** [comment]
for the future we might wanna make sure to merge them into dev

looks good though

**Comment by calcitem** [comment]
Merged to dev.

**Pull request merged**
