### PR TITLE
 fix some drawer stuff fixes #358 and fixes #351

### LINKED ISSUE #351: The title in the title bar and the dynamic icon in the upper left corner are not aligned
The title in the title bar and the dynamic icon in the upper left corner are not aligned.

The normal situation is shown in the screenshot below:

The abnormal display effect on the dev branch is as follows

As you can see, the icon in the upper left corner is not centered in the upper left corner, but to the upper side.

### LINKED ISSUE #358: The drawer is not sensitive to gestures
Need to adjust the parameters, and allow the drawer itself to respond to sliding gestures.

Refer to Outlook app or other well-known apps.

### PR DESCRIPTION
**Pull request by Leptopoda**
regarding #358 I did fix a bug where the threshold wasn't calculated properly. I also implemented a a dependency to the sliding velocity to override the needed threshold. 

If the drawer is not right you should fine tune both thresholds (the one of the velocity and the drag one).

### CODE REVIEW

**Comment by calcitem** [comment]
It seems that the distance between the board and the upper edge of the screen has become significantly longer.

I feel that the default value of `boardTop` has been modified, but the relevant code is not found. Maybe an offset value has been added? This may make the small screen device unable to display the toolbar.

**Comment by Leptopoda** [comment]
> It seems that the distance between the board and the upper edge of the screen has become significantly longer.
> 
> I feel that the default value of `boardTop` has been modified, but the relevant code is not found. Maybe an offset value has been added? This may make the small screen device unable to display the toolbar.

It's because I've added an appBar to the gamePage.
fix is coming

**Comment by calcitem** [comment]
I also found a very strange phenomenon before. When switching to the RTL layout, the boardTop will become smaller, so I manually added an offset value. So after the modification is completed, it is recommended to switch the system language to Arabic or Persian and restore the default settings to see the effect.

**Comment by calcitem** [comment]
The board is slightly higher.

```dart
this.boardTop = boardTop ?? (isLargeScreen ? 75.0 : 36.0);
```

This default value may need to be fine-tuned.

I will test on some different models of mobile phones, find an optimal value, and then commit a new adjustment.

**Comment by calcitem** [comment]
After comparison, it is found that no matter whether it is a large screen or a small screen, the boardTop actually has no change and no adjustment is required!

**Pull request merged**
