### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by calcitem**
Thanks for taking the time to contribute to Sanmill!

Nevertheless, you can use [GitHub](https://github.com/calcitem/Sanmill) to send your Pull Requests commits to us conveniently.

In addition, we highly recommend you read our submission guidelines.

Your friendly Sanmill community!

### CODE REVIEW

**Comment by Leptopoda** [comment]
Seems good so far.

I have a few cosmetic changes in mind and will push them later

**Comment by calcitem** [comment]
Do you mean we need to give some concrete examples to contributors?

**Comment by Leptopoda** [comment]
> Do you mean we need to give some concrete examples to contributors?

No I mean the other. I think it's to much. Why should we need to explain how to fork?
Most people know this and those who don't can just use a search engine. 

IMO the contributing guide should just explain our workflow and not how to use hit or so...
The more write the less likely it is that someone reads it. We need to keep it short so it'll be read.

**Comment by calcitem** [comment]
Your opinion is great, other content can be move to other .md files for view.

**Comment by Leptopoda** [comment]
Not only other md files but maybe the wiki

**Comment by Leptopoda** [comment]
Have a look at one of my [Contributing.md](https://github.com/Leptopoda/bierverkostung/blob/master/CONTRIBUTING.md) files.

It is small and clear. Within a few seconds everyone knows what to do. We could use this as a template and link to a wiki post (containing your current version) for beginners. 
We would also need to adapt the link for auto closing issues as it refers to the gitlab docs.

**Comment by calcitem** [comment]
I referred to this document before:

https://github.com/git/git/blob/master/.github/CONTRIBUTING.md

I will read your link in detail.

**Comment by Leptopoda** [comment]
You're right I copied it from the nextcloud repo. I forgot that so sorry for not mentioning it 😅

**Comment by calcitem** [comment]
Thanks for your advice! This document has been simplified based on your suggestions. Because the CI best practice certification is currently underway, this PR will be merged. If it needs to be revised, we can make a new Git commit later.

**Pull request merged**
