### PR TITLE
About page

### PR DESCRIPTION
**Pull request by calcitem**
This repository ("Code - OSS") is where Calcitem develops the Sanmill product together with the community, not only Calcitem. So need to remove the copyright text.

Show Git branch and revision on about dialog.

### CODE REVIEW

**Comment by Leptopoda** [comment]
Why is the git branch needed?

Also why didn't you wait for a review🙁

**Comment by calcitem** [comment]
Will there be any problems with git branch? This will not contain any privacy.

`More` contains Flutter channel (stable/dev, etc.) similar to branch. Therefore, this may be a regular practice.

There is no risk in this modification, and it is urgently needed, so I merged it first.

This commit  will not break the build. If there is a problem, we can make a new fix later.

**Comment by Leptopoda** [comment]
> and it is urgently needed

For what? I don't see the reason so please help me understand it🙃

**Comment by calcitem** [comment]
The storage of Github Action is not unlimited, it deletes builds periodically.  If a user who tries the apk reports a issue with the app in his hand, who knows which Git commit corresponds to?  

In the Android firmware version, the method of carrying a hexadecimal hash at the end is also used.

**Comment by Leptopoda** [comment]
So you need it when the user installs a dev apk from the CI.

The only question that remains is: why should a user be using the dev apk? And if someone does so they'll at least know where they got it from ...

**Comment by calcitem** [comment]
Some users who are very interested in the mill app trial are willing to experience new features and are willing to try them. 

They are in Sanmill's telegram group.

**Comment by calcitem** [comment]
Even if I test locally, sometimes I need to switch git bisect tests between many commits, and sometimes I forget which version I am testing.

**Comment by Leptopoda** [comment]
> Some users who are very interested in the mill app trial are willing to experience new features and are willing to try them.

that's something for the beta channel thus they'll only need to test changes once the dev branch is ready to be merged into master. In this case there won't be any confusion as there aren't multiple calls for testing per version.

> Even if I test locally, sometimes I need to switch git bisect tests between many commits, and sometimes I forget which version I am testing.

In this case that should probably be hidden behind the devMode flag. We might wanna add an extra flag for CI option passed to the build process. I'll have a think when the big PR is done ;)

**Comment by calcitem** [comment]
It is a common practice in the industry to display detailed version information in a certain way in the official version.  I really don't understand why it must be deleted in the version released to users?  Is it just to save dozens of bytes of space?

Life always gives you surprises and surprises inadvertently. Even the mobile app has easter eggs left by various developers. I don’t know if you have a pair of eyes that are good at discovering in front of the screen to enjoy these inconspicuous but inconspicuous eyes.  Make you laugh for fun.

Example: Continuously click the icon in the About dialog box of WeChat, the following dialog box will be displayed:

**Comment by Leptopoda** [comment]
I'm not against some information but i think the [KISS](https://en.wikipedia.org/wiki/KISS_principle) development strategy is preferable.
Also people don't like to see "cryptic" information. Lastly I'm not against this exact use case:
> We might wanna add an extra flag for CI option passed to the build process. I'll have a think when the big PR is done ;)

But I'm against the way it's implemented. You currently need to run the init script before build. I agree that some stuff like build_runner needs to be run but other stuff should be integrated into the build system (that's what gradle or build runner are made for). I think having a separate script you need to call separately (that's even in another folder) is cumbersome as a development workflow. 
Wrapping up the stuff we shouldn't create a text file with our variables that then needs to be parsed at runtime. Both the file representation and the runtime getting/parsing adds unnecessary overhead. We should either use

**Comment by calcitem** [comment]
If the user is confused about the hexadecimal Commit ID, we can consider hiding it.  But I still think this information is needed for the release version.  

It is currently displayed temporarily in the version dialog because the hidden environment variables have been removed.  The subsequent presentation can be discussed again.  

Yes I alsohop this information can be automatically generated during building, and it can be followed to locate a specific commit.

**Comment by calcitem** [comment]
build specific number is not enouph. As I said before, CI builds maybe deleted automaticly by GitHub.

**Comment by calcitem** [comment]
VSCode

image

**Pull request merged**
