### PR TITLE
Preferences

### PR DESCRIPTION
**Pull request by calcitem**
Move auto-restart option to misc card and restore the sound card

Revert playSounds removed by commit fcd8eae98fd9e97a6088cb508de2d06a465e5991

### CODE REVIEW

**Comment by calcitem** [comment]
No conflicts with https://github.com/calcitem/Sanmill/pull/421

**Comment by Leptopoda** [comment]
The audio on windows pr hasn't been merged yet so why did you enable the settings for windows?

**Comment by calcitem** [comment]
The impact is limited. Windows can’t make a sound is a minor problem, and there are many more serious problems than this.

**Comment by calcitem** [comment]
Thanks for reminding me. I just made up the fix.
https://github.com/calcitem/Sanmill/pull/427

However, the current dev branch is precarious and often crashes. So I don't think anyone cares about this sound problem under Windows, so I just make it lazily.

**Comment by Leptopoda** [comment]
Thats the reson for dev... Nobody should rely on it thus this is ok.

As you mentioned this was just a reminder

**Pull request merged**
